### ISSUE TITLE
Datastream#content_changed? should consider declared but unused namespace significant on controlGroup X

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/rubydora#80]
Will require new feature of equivalent-xml: https://github.com/mbklein/equivalent-xml/issues/21.

Can work around temporarily by comparing namespaces of the Nokogiri docs.

**Comment by mbklein** [comment]
@dchandekstark: I'm closing out stale issues on equivalent-xml. Is this still a feature that you need? If so, I'll add a milestone for mbklein/equivalent-xml#21. Otherwise, I'm going to close it.

**Comment by dchandekstark** [comment]
I don't think we need this feature going forward.
