### ISSUE TITLE
Travis build fails on Java errors

### ISSUE THREAD

**Issue by atz** [projecthydra/rubydora#94]
Local tests pass, but Travis croaks now.  It croaked on my first revision that only touched README, so I re-ran the last build from a year ago… also fails:
   https://travis-ci.org/projecthydra/rubydora/builds/40822458

Java error:
```
java.lang.UnsupportedClassVersionError: org/eclipse/jetty/servlet/listener/ELContextCleaner : Unsupported major.minor version 52.0
```

So this is probably a hydra-jetty problem or something we have to tweak for JVM in Travis.

**Comment by atz** [comment]
Switching to Oracle JDK 8 allowed the tests to run.  But now get 47 failures, e.g.:

https://travis-ci.org/projecthydra/rubydora/jobs/88228887

**Comment by atz** [comment]
Probably hydra-jetty (master) has moved further than rubydora is ready to accommodate.  It should be using properly versioned artifacts and not just attempting to track master, especially since it was untouched for a year or more and now we have no idea what actual hydra-jetty version ZIP file was the last one that worked.

**Comment by awead** [comment]
You'll need to pin the hydra-jetty version to 7.2.0, which is the version with Fedora 3.8.

**Comment by cbeer** [comment]
Fixed in https://github.com/projecthydra/rubydora/pull/95.
